spec-version:        0.36.0
name:                advent-haskell
version:             0.1.0.0
github:              "tobeannouncd/advent-haskell"
license:             BSD-3-Clause
author:              "tobeannouncd"
maintainer:          "tobeannouncd@gmail.com"
copyright:           "2024 Tyler Aas"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tobeannouncd/advent-haskell#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

language: GHC2021

default-extensions:
- LambdaCase
- BlockArguments

library:
  source-dirs: src
  dependencies:
  - advent-of-code-api
  - optparse-applicative
  - text
  - bytestring
  - mtl
  - parsec
  - containers
  - time

executables:
  advent-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-haskell

tests:
  advent-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-haskell
